# -*- coding: utf-8 -*-
from pathlib import Path
lines = []
def L(s=""): lines.append(s)

L('import { DragEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";')
L('import {')
L('  DocumentItem,')
L('  UploadTaskItem,')
L('  EXTERNAL_OCR_SIZE_THRESHOLD_BYTES,')
L('  ExternalOcrConfirmRequiredError,')
L('  resumeChunkUploadAfterExternalOcrConfirm,')
L('  getAccessToken,')
L('  fetchTenantQuotaStatus,')
L('  buildLocalProcessSnapshot,')
L('  CHUNK_UPLOAD_THRESHOLD,')
L('  downloadCloudDocumentOriginal,')
L('  type TenantQuotaStatus,')
L('} from "../hooks/useDocuments";')
L('import {')
L('  listLocalGuestDocuments,')
L('  putLocalGuestDocument,')
L('  deleteLocalGuestDocument,')
L('  type LocalGuestDoc,')
L('} from "../lib/localGuestDocuments";')
L('import {')
L('  deleteLocalUserBackup,')
L('  downloadOriginalBlob,')
L('  downloadProcessSnapshotJson,')
L('  listLocalUserBackups,')
L('  putLocalUserBackup,')
L('  localDraftProcessJson,')
L('  type LocalProcessSnapshot,')
L('  type LocalUserBackupRecord,')
L('} from "../lib/localUserBackup";')
L('import { GPU_OCR_PAGE_PACKS } from "../config/gpuOcrPricing";')
L('')
L('function fileKey(f: File): string {')
L('  return `${f.name}-${f.size}-${f.lastModified}`;')
L('}')
L('')
Path('frontend/src/tabs/UploadTab.tsx').write_text('\n'.join(lines) + '\n', encoding='utf-8')
print('partial', len(lines))
