import codecs, textwrap
# Full UploadTab content embedded as list of lines to avoid escaping hell
p = r"frontend/src/tabs/UploadTab.tsx"
lines = []
def add(*a):
    for x in a: lines.append(x)

add('import { DragEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";')
add('import {')
add('  DocumentItem,')
add('  UploadTaskItem,')
add('  EXTERNAL_OCR_SIZE_THRESHOLD_BYTES,')
add('  ExternalOcrConfirmRequiredError,')
add('  resumeChunkUploadAfterExternalOcrConfirm,')
add('  getAccessToken,')
add('  fetchTenantQuotaStatus,')
add('  buildLocalProcessSnapshot,')
add('  CHUNK_UPLOAD_THRESHOLD,')
add('  downloadCloudDocumentOriginal,')
add('  type TenantQuotaStatus,')
add('} from "../hooks/useDocuments";')
add('import {')
add('  listLocalGuestDocuments,')
add('  putLocalGuestDocument,')
add('  deleteLocalGuestDocument,')
add('  type LocalGuestDoc,')
add('} from "../lib/localGuestDocuments";')
add('import {')
add('  deleteLocalUserBackup,')
add('  downloadOriginalBlob,')
add('  downloadProcessSnapshotJson,')
add('  listLocalUserBackups,')
add('  putLocalUserBackup,')
add('  localDraftProcessJson,')
add('  type LocalProcessSnapshot,')
add('  type LocalUserBackupRecord,')
add('} from "../lib/localUserBackup";')
add('import { GPU_OCR_PAGE_PACKS } from "../config/gpuOcrPricing";')
add('')
add('function fileKey(f: File): string {')
add('  return `${f.name}-${f.size}-${f.lastModified}`;')
add('}')
add('')
# ... truncated for brevity in this message - I'll use exec to load rest from file
open("_ut_body.py","w",encoding="utf-8").write("")
